# Generated by Django 4.0.3 on 2022-03-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.PositiveSmallIntegerField(default=400, verbose_name='Rate'),
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winColor', models.CharField(max_length=10, verbose_name='End')),
                ('dateOfGame', models.DateTimeField(auto_now_add=True, verbose_name='Time of game')),
                ('moves', models.TextField(default=0, max_length=1000, verbose_name='Moves')),
                ('blackPlayer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rate.profile')),
                ('whitePlayer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rate.profile')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
