# Generated by Django 4.0.3 on 2022-04-15 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_remove_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='RD',
            field=models.PositiveSmallIntegerField(default=350, verbose_name='RD'),
        ),
        migrations.AlterField(
            model_name='games',
            name='whitePlayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='rate.profile'),
        ),
    ]
