# Generated by Django 4.0.3 on 2022-04-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_alter_games_whiteplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='whitePlayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='rate.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RD',
            field=models.PositiveSmallIntegerField(default=400, verbose_name='Rate'),
        ),
    ]
